import { INVALID_OPTION_MESSAGE, SERVICE_UNAVAILABLE_MESSAGE } from './engine'
import type { Flow, Screen } from './flow'
import { validateFlow } from './validate'

/**
 * Code generators for standalone USSD servers.
 *
 * Each target embeds the flow as data and ports the routing algorithm from
 * `lib/engine.ts` line for line, so the exported server answers every input
 * exactly as the in-browser simulator does. Both servers speak the common
 * gateway callback format (Africa's Talking style): a form-encoded POST with a
 * `text` field, answered with a plain-text "CON ..." or "END ..." body.
 */

export type ExportTarget = 'express' | 'fastapi'

export interface GeneratedFile {
  filename: string
  language: 'javascript' | 'python'
  code: string
}

export class FlowHasErrorsError extends Error {
  constructor(count: number) {
    super(`Cannot generate code: the flow has ${count} validation error(s).`)
    this.name = 'FlowHasErrorsError'
  }
}

/**
 * The flow reduced to exactly the fields the runtime needs, in a stable order.
 * Everything in it is a string, object or array, so its JSON is also a valid
 * Python literal (JSON string escapes are a subset of Python's).
 */
export function toPortableFlow(flow: Flow): Flow {
  const nodes: Record<string, Screen> = {}
  for (const screen of Object.values(flow.nodes)) {
    nodes[screen.id] = {
      id: String(screen.id),
      prompt: String(screen.prompt),
      kind: screen.kind === 'end' ? 'end' : 'menu',
      options:
        screen.kind === 'end'
          ? []
          : screen.options.map((o) => ({ key: String(o.key), label: String(o.label), next: String(o.next) })),
    }
  }
  return { start: String(flow.start), nodes }
}

function assertExportable(flow: Flow): Flow {
  const errors = validateFlow(flow).filter((p) => p.severity === 'error')
  if (errors.length > 0) throw new FlowHasErrorsError(errors.length)
  return toPortableFlow(flow)
}

export function generateExpress(flow: Flow): string {
  const data = JSON.stringify(assertExportable(flow), null, 2)
  return `// USSD server generated by USSD Flow Studio.
//
//   npm install express
//   node ussd-server.mjs            # listens on $PORT (default 3000)
//
// Point your USSD gateway's callback URL at POST /ussd. The gateway sends the
// caller's full input history as a '*'-joined "text" field ("" on first dial).

import express from 'express'

const FLOW = ${data}

function getScreen(id) {
  return Object.prototype.hasOwnProperty.call(FLOW.nodes, id) ? FLOW.nodes[id] : undefined
}

function render(screen) {
  if (screen.kind === 'end') return 'END ' + screen.prompt
  const lines = [screen.prompt, ...screen.options.map((o) => o.key + '. ' + o.label)]
  return 'CON ' + lines.join('\\n')
}

export function handleUssd(text) {
  let screen = getScreen(FLOW.start)
  if (!screen) return ${JSON.stringify(`END ${SERVICE_UNAVAILABLE_MESSAGE}`)}

  const keys = text === '' ? [] : text.split('*')
  for (const key of keys) {
    if (screen.kind === 'end') break
    const option = screen.options.find((o) => o.key === key)
    const next = option ? getScreen(option.next) : undefined
    if (!next) return ${JSON.stringify(`END ${INVALID_OPTION_MESSAGE}`)}
    screen = next
  }
  return render(screen)
}

const app = express()
app.use(express.urlencoded({ extended: false }))

app.post('/ussd', (req, res) => {
  const text = typeof req.body?.text === 'string' ? req.body.text : ''
  res.type('text/plain').send(handleUssd(text))
})

const server = app.listen(Number(process.env.PORT ?? 3000), () => {
  console.log('USSD server listening on port ' + server.address().port)
})
`
}

export function generateFastAPI(flow: Flow): string {
  const data = JSON.stringify(assertExportable(flow), null, 4)
  return `"""USSD server generated by USSD Flow Studio.

    pip install fastapi uvicorn python-multipart
    uvicorn ussd_app:app --port 8000

Point your USSD gateway's callback URL at POST /ussd. The gateway sends the
caller's full input history as a '*'-joined "text" field ("" on first dial).
"""

from fastapi import FastAPI, Form
from fastapi.responses import PlainTextResponse

FLOW = ${data}


def get_screen(screen_id):
    return FLOW["nodes"].get(screen_id)


def render(screen):
    if screen["kind"] == "end":
        return "END " + screen["prompt"]
    lines = [screen["prompt"]] + [o["key"] + ". " + o["label"] for o in screen["options"]]
    return "CON " + "\\n".join(lines)


def handle_ussd(text: str) -> str:
    screen = get_screen(FLOW["start"])
    if screen is None:
        return ${JSON.stringify(`END ${SERVICE_UNAVAILABLE_MESSAGE}`)}

    keys = text.split("*") if text != "" else []
    for key in keys:
        if screen["kind"] == "end":
            break
        option = next((o for o in screen["options"] if o["key"] == key), None)
        nxt = get_screen(option["next"]) if option is not None else None
        if nxt is None:
            return ${JSON.stringify(`END ${INVALID_OPTION_MESSAGE}`)}
        screen = nxt
    return render(screen)


app = FastAPI()


@app.post("/ussd", response_class=PlainTextResponse)
async def ussd(text: str = Form("")) -> str:
    return handle_ussd(text)
`
}

export function generate(target: ExportTarget, flow: Flow): GeneratedFile {
  return target === 'express'
    ? { filename: 'ussd-server.mjs', language: 'javascript', code: generateExpress(flow) }
    : { filename: 'ussd_app.py', language: 'python', code: generateFastAPI(flow) }
}
